from __future__ import annotations


def generate_sigma_rule(node_data: dict) -> str:
    node = str(node_data.get("node", "unknown")).replace("'", "''")
    confidence = node_data.get("confidence_pct", 0)
    top_ua = str(node_data.get("fingerprint_detail", {}).get("top_ua", "")).replace("'", "''")
    period = node_data.get("beacon_detail", {}).get("dominant_period_sec")
    iat_std = node_data.get("beacon_detail", {}).get("iat_std")

    return f"""title: PHANTOM TRACE - Detected C2 Beacon from {node}
status: experimental
description: Auto-generated by PHANTOM TRACE attribution engine. Node scored {confidence}% confidence.
logsource:
    category: network
    product: zeek
detection:
    selection:
        src_ip: '{node}'
        http.user_agent|contains: '{top_ua}'
    timing:
        # Beaconing detected at {period}s intervals
        # IAT std deviation: {iat_std}
    condition: selection
falsepositives:
    - Legitimate scheduled API polling
level: high
tags:
    - attack.command_and_control
    - attack.t1071
"""
